const ACCESS_TOKEN_EXPIRES = process.env.ACCESS_TOKEN_EXPIRES || '15m';
const REFRESH_TOKEN_DAYS = Number(process.env.REFRESH_TOKEN_DAYS || 7);
const REMEMBER_REFRESH_TOKEN_DAYS = Number(process.env.REMEMBER_REFRESH_TOKEN_DAYS || 30);
const CANCELLATION_WINDOW_HOURS = Number(process.env.CANCELLATION_WINDOW_HOURS || 24);
const ZOOM_MAX_CONCURRENT = Number(process.env.ZOOM_MAX_CONCURRENT || 10);
const STUDIO_NAME = process.env.STUDIO_NAME || 'Pulsed';

module.exports = {
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_DAYS,
  REMEMBER_REFRESH_TOKEN_DAYS,
  CANCELLATION_WINDOW_HOURS,
  ZOOM_MAX_CONCURRENT,
  STUDIO_NAME,
};
